spin_manifest_version = "1"
authors = ["MikeTeddyOmondi <mike_omondi@outlook.com>"]
description = "todo spin api"
name = "todo-spin-app"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "api"
source = "api/target/api.wasm"
[component.trigger]
route = "/api"
[component.build]
command = "npm run build"
workdir = "api"

[[component]]
source = "./fileserver/spin_static_fs.wasm"
id = "ui"
files = [ { source = "./ui/dist", destination = "/" } ]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
workdir = "ui"
 